spring.application.name=SpringEcom
server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url = jdbc:postgresql://localhost:5432/TestDb
spring.datasource.username = postgres
spring.datasource.password = admin
spring.datasource.hikari.auto-commit = false

spring.jpa.hibernate.ddl-auto = update