spring:
  application:
    name: SpingAI
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        timeout: 60s
        max-retries: 1
      chat:
        options:
          model: llama3.2