spring.application.name=sprint-security
spring.security.user.name = shubham
spring.security.user.password = 1234
server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url = jdbc:postgresql://localhost:5432/TestDb
spring.datasource.username = postgres
spring.datasource.password = admin
